
[Novice]
JobRank = 0
[Novice.SkillTree]
BasicMastery = []
FirstAid = [["BasicMastery", 8]]

[Swordsman]
JobRank = 1
Extends = "Novice"
[Swordsman.SkillTree]
#SwordMastery = []
#TwoHandSwordMastery = [["SwordMastery", 1]]
#IncreasedHPRecovery = []
Bash = []
#MagnumBreak = [["Bash", 5]]
Provoke = []
#Endure = [["Provoke", 5]]
TwoHandQuicken = [["Bash", 10], ["Provoke", 5]] #just for testing

[Archer]
JobRank = 1
Extends = "Novice"
[Archer.SkillTree]
DoubleStrafe = []
#ArrowShower = []
#ImproveConcentration = []

[Mage]
JobRank = 1
Extends = "Novice"
[Mage.SkillTree]
#IncreaseSPRecovery = []
FireBolt = []
#FireBall = [["FireBolt", 4]]
#FireWall = [["FireBall", 5]]
LightningBolt = []
ThunderStorm = [["LightningBolt", 4]]
ColdBolt = []
#FrostDriver = [["ColdBolt", 5]]
#SoulStrike = []
#SafetyWall = [["SoulStrike", 5]]

[Acolyte]
JobRank = 1
Extends = "Novice"
[Acolyte.SkillTree]
IncreaseSPRecovery = []
Heal = []
#Blessing = []
#IncreaseAgility = []

[Thief]
JobRank = 1
Extends = "Novice"
[Thief.SkillTree]
DoubleAttack = []
ImproveDodge = []

[Merchant]
JobRank = 1
Extends = "Novice"
[Merchant.SkillTree]
Mammonite = []
PushCart = []

